# -*- coding: utf-8 -*-
"""05_cluster_3D.py

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1IjYMMCZ74CJV1BIY78in57W9Jkgk-wKa
"""

import math

# Input titik U
x1 = 9
x2 = 7
x3 = 5

# Hitung jarak ke Cluster A (2, 1, 3)
jarakA = math.sqrt((x1 - 2)**2 + (x2 - 1)**2+ (x3 - 3)**2)

# Hitung jarak ke Cluster B (1, -4, 6)
jarakB = math.sqrt((x1 - 1)**2 + (x2 + 4)**2 + (x3 - 6)**2)

# Hitung jarak ke Cluster C (-2, 3, -2)
jarakC = math.sqrt((x1 + 2)**2 + (x2 - 3)**2 + (x3 + 2)**2)

# Menentukan cluster
if jarakA < jarakB and jarakA < jarakC:
    print("Titik U termasuk Cluster A")
elif jarakB < jarakA and jarakB < jarakC:
    print("Titik U termasuk Cluster B")
else:
    print("Titik U termasuk Cluster C")