# -*- coding: utf-8 -*-
"""Program 4 Project Alprog

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1vzJni9AWmf4WRxTjuBm10GIOjAg4xDqF

Program 4
"""

#Input NIP
nip=input("Masukkan NIP ASN:")

#Ambil Bagian Tanggal Lahir
tahun=nip[0:4]
bulan=nip[4:6]
tanggal=nip[6:8]

#Menentukan Bulan
if bulan=="01":
  nama_bulan="Januari"
elif bulan=="02":
  nama_bulan="Februari"
elif bulan=="03":
  nama_bulan="Maret"
elif bulan=="04":
  nama_bulan="April"
elif bulan=="05":
  nama_bulan="Mei"
elif bulan=="06":
  nama_bulan="Juni"
elif bulan=="07":
  nama_bulan="Juli"
elif bulan=="08":
  nama_bulan="Agustus"
elif bulan=="09":
  nama_bulan="September"
elif bulan=="10":
  nama_bulan="Oktober"
elif bulan=="11":
  nama_bulan="November"
elif bulan=="12":
  nama_bulan="Desember"

#Output
print("Tanggal lahir ASN:")
print(f"{tanggal} {nama_bulan} {tahun}")