# -*- coding: utf-8 -*-
"""Program 4 Projek Alpro

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1vzJni9AWmf4WRxTjuBm10GIOjAg4xDqF

Program 4
"""

#Input NIP
nip=input("Masukkan NIP ASN:")

#Ambil Bagian Tanggal Lahir
year=nip[0:4]
month=nip[4:6]
date=nip[6:8]

#Menentukan Bulan
if month=="01":
  name_of_month="Januari"
elif month=="02":
  name_of_month="Februari"
elif month=="03":
  name_of_month="Maret"
elif month=="04":
  name_of_month="April"
elif month=="05":
  name_of_month="Mei"
elif month=="06":
  name_of_month="Juni"
elif month=="07":
  name_of_month="Juli"
elif month=="08":
  name_of_month="Agustus"
elif month=="09":
  name_of_month="September"
elif month=="10":
  name_of_month="Oktober"
elif month=="11":
  name_of_month="November"
elif month=="12":
  name_of_month="Desember"

#Output
print("Tanggal lahir ASN:")
print(f"{date} {name_of_month} {year}")

#Input NIP
nip=input("Masukkan NIP ASN:")

#Ambil Bagian Tanggal Lahir
year=nip[0:4]
month=nip[4:6]
date=nip[6:8]

#Menentukan Bulan
if month=="01":
  name_of_month="Januari"
elif month=="02":
  name_of_month="Februari"
elif month=="03":
  name_of_month="Maret"
elif month=="04":
  name_of_month="April"
elif month=="05":
  name_of_month="Mei"
elif month=="06":
  name_of_month="Juni"
elif month=="07":
  name_of_month="Juli"
elif month=="08":
  name_of_month="Agustus"
elif month=="09":
  name_of_month="September"
elif month=="10":
  name_of_month="Oktober"
elif month=="11":
  name_of_month="November"
elif month=="12":
  name_of_month="Desember"

#Output
print("Tanggal lahir ASN:")
print(f"{date} {name_of_month} {year}")

#Input NIP
nip=input("Masukkan NIP ASN:")

#Ambil Bagian Tanggal Lahir
year=nip[0:4]
month=nip[4:6]
date=nip[6:8]

#Menentukan Bulan
if month=="01":
  name_of_month="Januari"
elif month=="02":
  name_of_month="Februari"
elif month=="03":
  name_of_month="Maret"
elif month=="04":
  name_of_month="April"
elif month=="05":
  name_of_month="Mei"
elif month=="06":
  name_of_month="Juni"
elif month=="07":
  name_of_month="Juli"
elif month=="08":
  name_of_month="Agustus"
elif month=="09":
  name_of_month="September"
elif month=="10":
  name_of_month="Oktober"
elif month=="11":
  name_of_month="November"
elif month=="12":
  name_of_month="Desember"

#Output
print("Tanggal lahir ASN:")
print(f"{date} {name_of_month} {year}")