# -*- coding: utf-8 -*-
"""Program1.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1KTFITPchTlDvuAupkSHxjZ6sUIoacwkk
"""

# PROGRAM 1
# Input teks dari pengguna
teks = input("Masukkan teks: ")

# Menghitung jumlah kalimat
jumlah_kalimat = teks.count(".")

# Menghapus tanda titik agar tidak dihitung sebagai kata
teks_bersih = teks.replace(".", "")

# Memisahkan teks menjadi kata-kata
kata = teks_bersih.split()

# Menghitung jumlah kata
jumlah_kata = len(kata)

# Menampilkan hasil
print("\nTeks tersebut memuat", jumlah_kalimat,
      "kalimat dan", jumlah_kata, "kata.")