# -*- coding: utf-8 -*-
"""Untitled3.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1CEBzFMgclKMnNeSWEW-PI_VON2x1j83u
"""

import math

# Membaca koefisien a, b, c
a = float(input("Masukkan nilai a: "))
b = float(input("Masukkan nilai b: "))
c = float(input("Masukkan nilai c: "))

# Menghitung diskriminan
D = b**2 - 4*a*c

# Menentukan jenis akar
if D > 0:
    x1 = (-b + math.sqrt(D)) / (2*a)
    x2 = (-b - math.sqrt(D)) / (2*a)
    print(f"Akar-akar real: x1 = {x1:.3f}, x2 = {x2:.3f}")
elif D == 0:
    x = -b / (2*a)
    print(f"Hanya satu akar real: x = {x:.3f}")
else:
    real_part = -b / (2*a)
    imag_part = math.sqrt(-D) / (2*a)
    print(f"Akar-akar imajiner: x1 = {real_part:.3f} + {imag_part:.3f}i, x2 = {real_part:.3f} - {imag_part:.3f}i")